# Generated by Django 2.2.6 on 2019-11-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='signup_confirmation',
        ),
        migrations.AddField(
            model_name='profile',
            name='business_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
