# Generated by Django 2.2.6 on 2019-11-23 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_profile_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('profile_status', 'Can register the posts and customers, also decide the status of requests')]},
        ),
    ]
