# Generated by Django 2.2.6 on 2019-11-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191102_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='business_number',
            new_name='bizNumber',
        ),
        migrations.AddField(
            model_name='profile',
            name='password1',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='password2',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
