# Generated by Django 2.2.6 on 2019-11-03 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20191103_0347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='nickname',
            new_name='nickName',
        ),
    ]
