# Generated by Django 2.2.6 on 2019-11-03 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20191104_0841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='nickName',
            new_name='nickname',
        ),
    ]
