# Generated by Django 2.2.6 on 2019-11-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='how_many',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
