# Generated by Django 2.2.6 on 2019-11-13 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_cart', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='food.Cart')),
            ],
        ),
    ]
