# Generated by Django 2.2.6 on 2019-11-18 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='how_many',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='food.Cart3'),
        ),
    ]
