# Generated by Django 2.2.5 on 2019-09-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20190922_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
