# Generated by Django 2.2.6 on 2019-11-17 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20191118_0141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
