# Generated by Django 2.2.6 on 2019-11-13 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0002_cart2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart2',
            name='approved_cart',
        ),
        migrations.AddField(
            model_name='cart2',
            name='people',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart2',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='cart2',
            name='request_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cart2',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cart2',
            name='title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='food.Food'),
        ),
        migrations.AddField(
            model_name='cart2',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
