# Generated by Django 2.2.6 on 2019-11-18 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20191118_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='how_many',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='food.Cart3'),
        ),
    ]
