# Generated by Django 2.2.6 on 2019-11-18 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20191118_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='how_many2',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
