# Generated by Django 2.2.6 on 2019-11-09 00:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('food', '0003_auto_20191107_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='author',
            new_name='sender',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='post',
        ),
        migrations.AddField(
            model_name='cart',
            name='reciever',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='cart',
            name='request_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cart',
            name='people',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
