# Generated by Django 2.2.6 on 2019-11-13 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20191113_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart2',
            name='id',
        ),
        migrations.AddField(
            model_name='cart2',
            name='order_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='food.Cart'),
        ),
        migrations.AddField(
            model_name='cart2',
            name='status',
            field=models.CharField(choices=[('-1', 'failed'), ('0', 'pending'), ('1', 'approved')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='cart2',
            name='tid',
            field=models.CharField(default='default', max_length=25, primary_key=True, serialize=False),
        ),
    ]
