# Generated by Django 2.2.6 on 2019-11-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20191113_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart2',
            name='order_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
