# Generated by Django 2.2.5 on 2019-10-12 16:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_food_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=10, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
    ]
