# Generated by Django 2.2.6 on 2019-11-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20191109_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
