# Generated by Django 2.2.6 on 2019-11-14 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20191113_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='sender',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
