# Generated by Django 2.2.5 on 2019-10-26 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20191013_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='category2',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
    ]
