# Generated by Django 2.2.6 on 2019-11-10 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_auto_20191110_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='food.Food'),
        ),
    ]
