# Generated by Django 2.2.6 on 2019-11-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_alarm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer',
            field=models.CharField(max_length=30),
        ),
    ]
