# Generated by Django 2.2.6 on 2019-11-14 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_auto_20191114_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart2',
            name='status',
            field=models.CharField(choices=[('-1', 'failed'), ('0', 'pending'), ('1', 'approved')], default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='cart2',
            name='tid',
            field=models.CharField(default='default', max_length=30, primary_key=True, serialize=False),
        ),
    ]
