# Generated by Django 2.2.6 on 2019-11-10 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_cart_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='reciever',
            new_name='receiver',
        ),
    ]
