# Generated by Django 2.2.6 on 2019-11-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.IntegerField(default='', null=True, verbose_name='price'),
        ),
    ]
