# Generated by Django 2.2.6 on 2019-11-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_successcart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='successcart',
            name='id',
        ),
        migrations.AddField(
            model_name='successcart',
            name='suc_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
