# Generated by Django 2.2.6 on 2019-11-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_remove_customer_how_many2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='reason',
            field=models.CharField(max_length=100),
        ),
    ]
