# Generated by Django 2.2.6 on 2019-11-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_auto_20191103_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
