# Generated by Django 2.2.6 on 2019-11-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_auto_20191103_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.IntegerField(blank=True, default='1', null=True),
        ),
    ]
