# Generated by Django 2.2.6 on 2019-11-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_auto_20191123_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cart2',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
