# Generated by Django 2.2.6 on 2019-11-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_auto_20191103_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.IntegerField(default=1),
        ),
    ]
