# Generated by Django 2.2.6 on 2019-11-03 14:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0014_auto_20191103_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=20, verbose_name='price'),
        ),
    ]
