# Generated by Django 2.2.6 on 2019-11-04 00:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0018_auto_20191104_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
