# Generated by Django 2.2.6 on 2019-11-04 00:59

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0019_auto_20191104_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
